"""
Accommodation data module for MBS Reports projects.

This module contains separate files for each project's accommodation data,
which is auto-generated by scripts/update_accommodation_data.py.
"""

