#!/usr/bin/env python3
"""
OpenPyXL Data Bars Fixer
========================

This utility fixes common issues with data bars generated by OpenPyXL:

1. **Gap/Padding Issues**: OpenPyXL creates data bars with padding/gaps at cell edges
   - Fix: Adds minLength="0" maxLength="100" to make bars span full cell width

2. **Gradient Control**: OpenPyXL cannot control gradient vs solid appearance 
   - Fix: Adds x14 namespace extensions with gradient controls

3. **Missing x14 Extensions**: OpenPyXL creates basic dataBar elements that Excel treats as gradient with padding
   - Fix: Creates complete x14:conditionalFormattings structure that Excel respects

AVAILABLE FIX OPTIONS:
- **remove-gaps**: Make bars span full cell width (minLength=0, maxLength=100)
- **make-solid**: Force bars to solid color (gradient=0) 
- **make-gradient**: Force bars to gradient effect (remove gradient=0)
- **full-fix**: Apply gap removal + your choice of solid/gradient (default: gradient)

USAGE:
------

**Command Line:**
    python openpyxl_databars_fixer.py myfile.xlsx --remove-gaps --make-solid
    python openpyxl_databars_fixer.py myfile.xlsx --full-fix --gradient
    python openpyxl_databars_fixer.py  # Interactive menu

**Programmatic (from other Python code):**
    from utils.openpyxl_databars_fixer import fix_databars
    fix_databars('myfile.xlsx', remove_gaps=True, solid=True)
    fix_databars('myfile.xlsx', remove_gaps=True, solid=False)  # Gradient with no gaps

**Batch Processing:**
    python openpyxl_databars_fixer.py *.xlsx --full-fix --gradient

TECHNICAL DETAILS:
------------------
OpenPyXL creates XML like:
    <dataBar showValue="1"/>  # Basic element, Excel adds padding + gradient

This tool creates:
    <cfRule><extLst><x14:id>{uuid}</x14:id></extLst></cfRule>
    <extLst><x14:conditionalFormattings>
        <x14:dataBar minLength="0" maxLength="100" gradient="0">

Which gives full control over appearance that Excel respects.
"""

import argparse
import sys
import zipfile
import tempfile
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Optional, List
import uuid
import glob


def fix_databars(xlsx_path: str, remove_gaps: bool = True, solid: Optional[bool] = None, in_place: bool = True) -> Optional[Path]:
    """
    Fix OpenPyXL data bar issues by adding x14 namespace extensions.
    
    Args:
        xlsx_path: Path to Excel file
        remove_gaps: If True, make bars span full cell width (minLength=0, maxLength=100)
        solid: If True, make bars solid. If False, make gradient. If None, don't change gradient.
        in_place: If True, modify original file. If False, create new file with '_fixed' suffix.
    
    Returns:
        Path to fixed file if successful, None otherwise.
    """
    original_path = Path(xlsx_path)
    if not original_path.exists():
        print(f"Error: File not found at {xlsx_path}")
        return None

    temp_dir = Path(tempfile.mkdtemp())
    modified_file_path = None
    total_modified_databars = 0
    total_modified_sheets = 0

    try:
        # Extract workbook
        with zipfile.ZipFile(original_path, 'r') as zin:
            zin.extractall(temp_dir)

        # Namespaces for SpreadsheetML
        ns = {
            'main': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main',
            'x14': 'http://schemas.microsoft.com/office/spreadsheetml/2009/9/main'
        }

        # Register all necessary namespaces for proper XML generation
        ET.register_namespace('', 'http://schemas.openxmlformats.org/spreadsheetml/2006/main')
        ET.register_namespace('x14', 'http://schemas.microsoft.com/office/spreadsheetml/2009/9/main')
        ET.register_namespace('xm', 'http://schemas.microsoft.com/office/excel/2006/main')

        # Loop over worksheet XML files
        for sheet_file in (temp_dir / 'xl' / 'worksheets').glob('sheet*.xml'):
            tree = ET.parse(sheet_file)
            root = tree.getroot()

            modified_count = 0

            # Fix existing x14:dataBar elements (allow gradient/solid switching)
            existing_x14_databars = root.findall('.//x14:dataBar', ns)
            for data_bar in existing_x14_databars:
                needs_update = False

                # Handle gradient/solid switching (always allow this)
                if solid is True:
                    # Force solid
                    if data_bar.get('gradient') != '0':
                        data_bar.set('gradient', '0')
                        needs_update = True
                elif solid is False:
                    # Force gradient (remove gradient attribute)
                    if 'gradient' in data_bar.attrib:
                        del data_bar.attrib['gradient']
                        needs_update = True
                # If solid is None, don't change gradient setting

                # Handle gap removal
                if remove_gaps:
                    if data_bar.get('minLength') != '0':
                        data_bar.set('minLength', '0')
                        needs_update = True
                    if data_bar.get('maxLength') != '100':
                        data_bar.set('maxLength', '100')
                        needs_update = True
                    # Remove padding attributes that cause gaps
                    if 'negativeBarColorSameAsPositive' in data_bar.attrib:
                        del data_bar.attrib['negativeBarColorSameAsPositive']
                        needs_update = True
                    if 'axisPosition' in data_bar.attrib:
                        del data_bar.attrib['axisPosition']
                        needs_update = True

                if needs_update:
                    modified_count += 1

            # Find data bar rules that don't have x14 extensions and create them
            cf_elements = root.findall('.//main:conditionalFormatting', ns)
            x14_rules_to_create = []

            for cf in cf_elements:
                sqref = cf.get('sqref')
                rules = cf.findall('./main:cfRule[@type="dataBar"]', ns)

                for rule in rules:
                    # Check if this rule already has x14 extension
                    extlst = rule.find('./main:extLst', ns)
                    has_x14 = False

                    if extlst is not None:
                        for ext in extlst.findall('./main:ext', ns):
                            if ext.find('./x14:id', ns) is not None:
                                has_x14 = True
                                break

                    if not has_x14:
                        # Generate unique ID for this rule
                        rule_id = '{' + str(uuid.uuid4()).upper() + '}'

                        # Add extLst to the cfRule
                        if extlst is None:
                            extlst = ET.SubElement(rule, f"{{{ns['main']}}}extLst")

                        ext = ET.SubElement(extlst, f"{{{ns['main']}}}ext")
                        ext.set('uri', '{B025F937-C7B1-47D3-B67F-A62EFF666E3E}')

                        x14_id_elem = ET.SubElement(ext, f"{{{ns['x14']}}}id")
                        x14_id_elem.text = rule_id

                        # Get data bar info for x14 creation
                        databar = rule.find('./main:dataBar', ns)
                        cfvos = databar.findall('./main:cfvo', ns) if databar is not None else []
                        color_elem = databar.find('./main:color', ns) if databar is not None else None

                        # Store info for worksheet-level x14 extension
                        x14_rules_to_create.append({
                            'id': rule_id,
                            'sqref': sqref,
                            'cfvos': [(cfvo.get('type', 'num'), cfvo.get('val', '0')) for cfvo in cfvos],
                            'color': color_elem.get('rgb') if color_elem is not None else 'FF000000'
                        })

                        modified_count += 1

            # Create or update worksheet-level extLst with x14:conditionalFormattings
            if x14_rules_to_create:
                # Find or create worksheet extLst
                worksheet_extlst = root.find('./main:extLst', ns)
                if worksheet_extlst is None:
                    worksheet_extlst = ET.SubElement(root, f"{{{ns['main']}}}extLst")

                # Find or create the x14 conditionalFormattings ext
                x14_ext = None
                for ext in worksheet_extlst.findall('./main:ext', ns):
                    if ext.get('uri') == '{78C0D931-6437-407d-A8EE-F0AAD7539E65}':
                        x14_ext = ext
                        break

                if x14_ext is None:
                    x14_ext = ET.SubElement(worksheet_extlst, f"{{{ns['main']}}}ext")
                    x14_ext.set('uri', '{78C0D931-6437-407d-A8EE-F0AAD7539E65}')

                # Find or create x14:conditionalFormattings
                x14_cfs = x14_ext.find('./x14:conditionalFormattings', ns)
                if x14_cfs is None:
                    x14_cfs = ET.SubElement(x14_ext, f"{{{ns['x14']}}}conditionalFormattings")

                # Create x14:conditionalFormatting for each rule
                for rule_info in x14_rules_to_create:
                    x14_cf = ET.SubElement(x14_cfs, f"{{{ns['x14']}}}conditionalFormatting")

                    # Create x14:cfRule
                    x14_rule = ET.SubElement(x14_cf, f"{{{ns['x14']}}}cfRule")
                    x14_rule.set('type', 'dataBar')
                    x14_rule.set('id', rule_info['id'])

                    # Create x14:dataBar with specified settings
                    x14_databar = ET.SubElement(x14_rule, f"{{{ns['x14']}}}dataBar")
                    
                    # Apply gap removal settings
                    if remove_gaps:
                        x14_databar.set('minLength', '0')     # Start at cell edge
                        x14_databar.set('maxLength', '100')   # Go to cell edge

                    # Apply gradient/solid settings
                    if solid is True:
                        x14_databar.set('gradient', '0')      # Solid color
                    elif solid is False:
                        pass  # No gradient attribute = natural gradient effect

                    # Add cfvo elements
                    for cfvo_type, cfvo_val in rule_info['cfvos']:
                        x14_cfvo = ET.SubElement(x14_databar, f"{{{ns['x14']}}}cfvo")
                        x14_cfvo.set('type', cfvo_type)

                        # Create xm:f child element
                        xm_f = ET.SubElement(x14_cfvo, '{http://schemas.microsoft.com/office/excel/2006/main}f')
                        xm_f.text = cfvo_val

                    # Add sqref
                    xm_sqref = ET.SubElement(x14_cf, '{http://schemas.microsoft.com/office/excel/2006/main}sqref')
                    xm_sqref.text = rule_info['sqref']

            # Write back if modifications were made
            if modified_count > 0:
                tree.write(sheet_file, encoding='utf-8', xml_declaration=True)
                total_modified_databars += modified_count
                total_modified_sheets += 1

        # Repackage the edited ZIP
        if in_place:
            modified_file_path = original_path
        else:
            modified_file_path = original_path.with_name(original_path.stem + '_fixed.xlsx')

        # Create a new zip file
        with zipfile.ZipFile(modified_file_path, 'w', zipfile.ZIP_DEFLATED) as zout:
            import os
            for folder_name, subfolders, filenames in os.walk(temp_dir):
                for filename in filenames:
                    file_path = Path(folder_name) / filename
                    # Calculate relative path for the zip archive
                    arcname = file_path.relative_to(temp_dir)
                    zout.write(file_path, arcname)

        if total_modified_databars > 0:
            print(f"  ✓ Fixed {total_modified_databars} data bar(s) across {total_modified_sheets} sheet(s) in {original_path.name}")
        else:
            print(f"  ℹ No data bars found to fix in {original_path.name}")
            
        return modified_file_path

    except Exception as e:
        print(f"Error processing Excel file {original_path.name}: {e}")
        import traceback
        traceback.print_exc()
        return None
    finally:
        # Clean up temporary directory
        if temp_dir.exists():
            shutil.rmtree(temp_dir)


# Backward compatibility alias
def process_report_databars(xlsx_path: str, in_place: bool = True) -> Optional[Path]:
    """
    Backward compatibility function for existing reports.
    Applies full fix (remove gaps + gradient effect).
    """
    return fix_databars(xlsx_path, remove_gaps=True, solid=False, in_place=in_place)


def interactive_menu():
    """Interactive console menu for processing files."""
    print("\n" + "="*60)
    print("OpenPyXL Data Bars Fixer - Interactive Mode")
    print("="*60)
    print(__doc__.split('USAGE:')[0])  # Print description part only
    
    while True:
        print("\nSelect an option:")
        print("1. Fix single file")
        print("2. Fix multiple files (glob pattern)")
        print("3. Exit")
        
        choice = input("\nEnter choice (1-3): ").strip()
        
        if choice == '3':
            print("Goodbye!")
            break
        elif choice in ['1', '2']:
            if choice == '1':
                file_pattern = input("Enter Excel file path: ").strip()
                files = [file_pattern] if Path(file_pattern).exists() else []
            else:
                file_pattern = input("Enter glob pattern (e.g., *.xlsx, reports/*.xlsx): ").strip()
                files = glob.glob(file_pattern)
            
            if not files:
                print("No files found!")
                continue
                
            print(f"\nFound {len(files)} file(s): {files}")
            
            print("\nSelect fix type:")
            print("1. Remove gaps only (full-width bars, keep current gradient/solid)")
            print("2. Make solid only (keep current width)")
            print("3. Make gradient only (keep current width)")
            print("4. Full fix: Remove gaps + make solid")
            print("5. Full fix: Remove gaps + make gradient")
            
            fix_choice = input("Enter choice (1-5): ").strip()
            
            # Parse fix options
            if fix_choice == '1':
                remove_gaps, solid = True, None
            elif fix_choice == '2':
                remove_gaps, solid = False, True
            elif fix_choice == '3':
                remove_gaps, solid = False, False
            elif fix_choice == '4':
                remove_gaps, solid = True, True
            elif fix_choice == '5':
                remove_gaps, solid = True, False
            else:
                print("Invalid choice!")
                continue
            
            # Ask about in-place modification
            in_place = input("Modify files in-place? (y/n): ").strip().lower() == 'y'
            
            # Process files
            print(f"\nProcessing {len(files)} file(s)...")
            for file_path in files:
                result = fix_databars(file_path, remove_gaps=remove_gaps, solid=solid, in_place=in_place)
                if result is None:
                    print(f"  ✗ Failed to process {file_path}")
            
            print("\nProcessing complete!")
        else:
            print("Invalid choice!")


def main():
    """Main entry point for command line usage."""
    parser = argparse.ArgumentParser(
        description="Fix OpenPyXL data bar issues (gaps, gradient control)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s myfile.xlsx --remove-gaps --make-gradient
  %(prog)s reports/*.xlsx --full-fix --solid  
  %(prog)s file1.xlsx file2.xlsx --remove-gaps
  %(prog)s  # Interactive mode
        """
    )
    
    parser.add_argument('files', nargs='*', help='Excel files to process (supports glob patterns)')
    
    # Fix type options
    fix_group = parser.add_argument_group('Fix Options')
    fix_group.add_argument('--remove-gaps', action='store_true', 
                          help='Make bars span full cell width (minLength=0, maxLength=100)')
    fix_group.add_argument('--make-solid', action='store_true',
                          help='Force bars to solid color (gradient=0)')
    fix_group.add_argument('--make-gradient', action='store_true', 
                          help='Force bars to gradient effect (remove gradient=0)')
    fix_group.add_argument('--full-fix', action='store_true',
                          help='Apply gap removal + gradient/solid choice (default: gradient)')
    
    # Output options
    parser.add_argument('--in-place', action='store_true', default=True,
                       help='Modify files in-place (default)')
    parser.add_argument('--create-copy', action='store_true',
                       help='Create new files with _fixed suffix instead of modifying originals')
    
    args = parser.parse_args()
    
    # If no files specified, start interactive mode
    if not args.files:
        interactive_menu()
        return
    
    # Expand glob patterns
    all_files = []
    for pattern in args.files:
        if '*' in pattern or '?' in pattern:
            all_files.extend(glob.glob(pattern))
        else:
            all_files.append(pattern)
    
    if not all_files:
        print("No files found!")
        return
    
    # Parse fix options
    remove_gaps = args.remove_gaps or args.full_fix
    
    if args.make_solid and args.make_gradient:
        print("Error: Cannot specify both --make-solid and --make-gradient")
        return
    
    if args.full_fix:
        solid = not args.make_gradient  # Default to solid for full-fix unless gradient specified
    elif args.make_solid:
        solid = True
    elif args.make_gradient:
        solid = False
    else:
        solid = None  # Don't change gradient setting
    
    in_place = not args.create_copy
    
    # Process files
    print(f"Processing {len(all_files)} file(s)...")
    for file_path in all_files:
        result = fix_databars(file_path, remove_gaps=remove_gaps, solid=solid, in_place=in_place)
        if result is None:
            print(f"  ✗ Failed to process {file_path}")


if __name__ == '__main__':
    main()
